name: hello-world
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"

  second-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: My Action
        uses: ./.github/actions/test.yml

