name: Nginx DockerHub and S3 Push

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull Nginx Image from DockerHub
        run: docker pull nginx:latest

      - name: Tag Nginx Image DockerHub Username
        run: docker tag nginx:latest $DOCKERHUB_USERNAME/nginx:latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Push Nginx Image to DockerHub
        run: docker push $DOCKERHUB_USERNAME/nginx:latest

      - name: Install and Configure AWS CLI
        uses: aws-actions/configure-aws-cli@v1.1.0
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          region: us-west-1

      - name: Upload Latest Nginx Image to S3
        run: aws s3 cp $DOCKERHUB_USERNAME/nginx:latest s3://my-github-actions-bucket/latest/
