name: Workflow Name

on: 
 push:
  branches: main
  types: [trigger-workflow]

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Step Name
        run: |
          echo "Hello, world!"
