name: Workflow Name

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Step Name
        run: |
          echo "Hello, world!"
